# Generated by Django 4.1.4 on 2023-09-15 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_date_visit_date2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='date2',
            new_name='date',
        ),
    ]
